blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/yourusername/jspdf-table/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/yourusername/jspdf-table#readme
    about: Check the documentation for usage examples and API reference